name: Deploy to Azure Web Apps

on:
  push:
    branches:
      - main  # Change this to your default branch if different
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: your-app-name    # Set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: .         # Set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20.x'                 # Set this to the Node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: node-app
          path: .

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
