name: Deploy to Azure Web Apps

on:
  push:
    branches:
      - main  # Ensure this matches your branch name
  workflow_dispatch:  # Allows manual triggering of the workflow

env:
  AZURE_WEBAPP_NAME: your-app-name    # Set this to your Azure App Service name
  AZURE_WEBAPP_PACKAGE_PATH: .         # Set this to the path to your web app project
  NODE_VERSION: '20.x'                 # Specify the Node.js version to use

permissions:
  contents: read  # Grants read access to repository contents

jobs:
  build:
    runs-on: ubuntu-latest  # Specify the OS for the runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out your repository code

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Sets up Node.js environment
        with:
          node-version: ${{ env.NODE_VERSION }}  # Use Node version from env variable
          cache: 'npm'  # Caches npm dependencies for faster builds

      - name: Install dependencies, build, and test
        run: |
          npm install  # Install dependencies
          npm run build --if-present  # Build the project if a build script exists
          npm run test --if-present  # Run tests if a test script exists

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4  # Updated to v4 for artifact upload
        with:
          name: node-app  # Name of the artifact
          path: .         # Path to upload (current directory)

  deploy:
    runs-on: ubuntu-latest  # Specify the OS for the runner
    needs: build  # This job depends on the build job completing successfully
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2  # Download the artifact created in the build job
        with:
          name: node-app  # Name of the artifact to download

      - name: Deploy to Azure WebApp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2  # Action to deploy to Azure Web App
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}  # Name of your Azure app service
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Use secret for publish profile
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}  # Path to package for deployment
