name: Run JavaScript Script

on:
  workflow_dispatch:  # Allows manual triggering from the Actions tab

jobs:
  run-script:
    runs-on: ubuntu-latest  # Specifies the runner environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checks out your repository code

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'  # Specify the Node.js version

      - name: Install dependencies
        run: npm install  # Installs dependencies defined in package.json

      - name: Run script
        run: node script.js  # Executes your JavaScript file
